import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import * as Dialog from '@radix-ui/react-dialog';
import {CalendarDays,Users,Settings,Plus,ChevronLeft,ChevronRight,Search,RefreshCw,ArrowUpRight,Clock,MapPin,X,Check,CheckCheck,AlertCircle,BookOpen,Car,GraduationCap,StickyNote,ArrowRight,Download,LogOut,WifiOff,CalendarCheck,Link as LinkIcon,SlidersHorizontal,Activity} from 'lucide-react';
import {today,monday,addDays,weekday,minutes,clock,niceDate,stamp,instant,occurrences,conflicts,coverage,freeSlots,SOURCES,eventLanes} from './domain';
import './style.css';
const uid=()=>crypto.randomUUID();
const DAYS=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const icons={lesson:BookOpen,university:GraduationCap,driving:Car,personal:CalendarCheck};
async function api(url,method='GET',body){const r=await fetch('/api/'+url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json();}catch{throw new Error('Сервер недоступен');}if(!r.ok){const e=new Error(data.error||'Ошибка запроса');e.status=r.status;throw e;}return data;}
function Button({children,icon:Icon,className='',...props}){return <button className={'btn '+className} {...props}>{Icon&&<Icon size={16}/>} {children}</button>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,subtitle,children,onClose,wide=false}){return <Dialog.Root open onOpenChange={open=>!open&&onClose()}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className={'modal '+(wide?'wide':'')} onOpenAutoFocus={e=>e.preventDefault()}><header><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{subtitle||'Ритм · личное расписание'}</Dialog.Description></div><Dialog.Close asChild><button className="icon-button" aria-label="Закрыть"><X size={20}/></button></Dialog.Close></header>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
function App(){
 const [data,setData]=useState(null),[cache,setCache]=useState({}),[version,setVersion]=useState(0),[connections,setConnections]=useState({}),[login,setLogin]=useState(false),[offline,setOffline]=useState(false),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false);
 const [page,setPage]=useState('calendar'),[week,setWeek]=useState(window.RITM_PREVIEW_WEEK||monday(addDays(today(),weekday(today())===6?1:0))),[selected,setSelected]=useState(today()),[view,setView]=useState('week'),[filters,setFilters]=useState(Object.keys(SOURCES)),[modal,setModal]=useState(null),[query,setQuery]=useState('');
 const versionRef=useRef(0),loaded=useRef(false),busy=useRef(false),syncBusy=useRef(false);
 const cacheLocal=(state,c,v)=>{try{if(window.RITM_PREVIEW_WEEK)return;localStorage.setItem('ritm-cache',JSON.stringify({state,cache:c,version:v,savedAt:new Date().toISOString()}));}catch{}};
 async function load(){try{const r=await api('state');setData(r.state);setCache(r.cache);setVersion(r.version);versionRef.current=r.version;setConnections(r.connections);setOffline(false);setLogin(false);cacheLocal(r.state,r.cache,r.version);loaded.current=true;}catch(e){if(e.status===401){setLogin(true);return;}try{const saved=JSON.parse(localStorage.getItem('ritm-cache'));if(saved){setData(saved.state);setCache(saved.cache);setVersion(saved.version);versionRef.current=saved.version;setOffline(true);}else setMessage('Нет связи с сервером. Запустите сервер и обновите страницу.');}catch{setMessage(e.message);}}}
 useEffect(()=>{load();},[]);
 async function sync(target=week){if(syncBusy.current||offline)return;syncBusy.current=true;setSyncing(true);try{const r=await api('sync','POST',{week:target});setCache(r.cache);if(data)cacheLocal(data,r.cache,versionRef.current);}catch(e){setMessage(e.message);}finally{setSyncing(false);syncBusy.current=false;}}
 useEffect(()=>{if(data&&!offline&&!login)sync(week);},[week,!!data,offline,login]);
 useEffect(()=>{const focus=()=>{if(!document.hidden&&loaded.current&&!offline)sync(week);};const timer=setInterval(focus,15*60000);document.addEventListener('visibilitychange',focus);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',focus);};},[week,data,offline]);
 useEffect(()=>{if(selected<week||selected>=addDays(week,7))setSelected(week);},[week]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),8000);return()=>clearTimeout(t);},[message]);
 async function save(next){if(offline){setMessage('Нет связи: доступен просмотр сохранённого расписания.');return false;}if(busy.current)return false;busy.current=true;setSaving(true);try{const r=await api('state','PUT',{state:next,version:versionRef.current});setData(r.state);setVersion(r.version);versionRef.current=r.version;cacheLocal(r.state,cache,r.version);setMessage('Сохранено');return true;}catch(e){setMessage(e.message);return false;}finally{busy.current=false;setSaving(false);}}
 if(login)return <Login onLogin={load}/>;
 if(!data)return <div className="loading"><Activity size={34}/><h2>Собираем твой день</h2><p>{message||'Загружаем расписание…'}</p><Button onClick={load}>Повторить</Button></div>;
 const events=occurrences(data,addDays(week,-1),addDays(week,8),cache).filter(e=>e.date>=week&&e.date<addDays(week,7));
 const weekEvents=events.filter(e=>filters.includes(e.kind));
 const dayEvents=events.filter(e=>e.date===selected);
 const allSoon=occurrences(data,today(),addDays(today(),8),cache),upcoming=allSoon.find(e=>instant(e.end)>Date.now());
 const clashIds=new Set(events.filter(e=>conflicts(e,events,data.settings,e.id).some(x=>x.type==='overlap')).map(e=>e.id));
 const sources=coverage(cache,week),tusurWeek=cache['university:'+week]?.week;
 const unavailable=sources.filter(x=>!x.fresh);
 const slots=freeSlots(data,occurrences(data,addDays(week,-1),addDays(week,8),cache),selected,60).filter(t=>instant(stamp(selected,t))>Date.now());
 const newEvent=(date=selected,time='18:00')=>setModal({type:'event',date,time});
 const openEvent=e=>setModal({type:'detail',event:e});
 const nav=[['calendar',CalendarDays,'Расписание'],['students',Users,'Ученики'],['settings',Settings,'Настройки']];
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('calendar')}}><span className="brand-icon"><Activity size={24}/></span>ритм<span className="brand-dot">.</span></a><div className="workspace-label">ЛИЧНОЕ ПРОСТРАНСТВО</div><nav>{nav.map(([id,Icon,title])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={19}/>{title}{id==='students'&&<span>{data.students.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="calm-card"><span className="mini-mark">✳</span><h4>Всему своё время.</h4><p>Учёба, уроки и жизнь —<br/>в одном спокойном ритме.</p></div><div className="profile"><span className="avatar">А</span><div><b>Антон</b><small>Томск · UTC+7</small></div><button className="icon-button" aria-label="Выйти" onClick={async()=>{await api('logout','POST');localStorage.removeItem('ritm-cache');setData(null);setLogin(true)}}><LogOut size={16}/></button></div></div></aside>
 <main><div className="topbar"><div className="breadcrumb">Моё пространство <ChevronRight size={13}/> <b>{nav.find(n=>n[0]===page)[2]}</b></div><span className="save-indicator">{offline?<><WifiOff size={14}/> Сохранённая копия</>:saving?'Сохраняем…':<><span className="status-dot"/> На сервере</>}</span></div>
 {window.RITM_PREVIEW_WEEK&&<div className="notice">Автономный предпросмотр · снимок недели 21–27 сентября. Изменения сбрасываются при перезагрузке; живой синхронизации нет.</div>}{offline&&<div className="notice"><WifiOff size={17}/>Нет связи. Последняя сохранённая версия, редактирование отключено.<button onClick={load}>Подключиться</button></div>}
 <div className="page-content"><div className="page-title"><div><div className="eyebrow">{page==='calendar'?'ВРЕМЯ ПОД КОНТРОЛЕМ':page==='students'?'ВСЁ ВАЖНОЕ ПОД РУКОЙ':'ТВОИ ПРАВИЛА'}</div><h1>{page==='calendar'?'Твоя неделя':page==='students'?'Ученики':'Настройки'}</h1><p>{page==='calendar'?'Меньше держать в голове. Больше успевать.':page==='students'?'Открой карточку — и ты снова в контексте.':'Пусть расписание подстраивается под тебя.'}</p></div><div className="actions">{page==='calendar'&&<Button icon={Search} onClick={()=>setModal({type:'find'})}>Найти время</Button>}{page!=='settings'&&<Button icon={Plus} className="primary" disabled={offline} onClick={()=>page==='students'?setModal({type:'student'}):newEvent()}>{page==='students'?'Новый ученик':'Добавить'}</Button>}</div></div>
 {page==='calendar'?<><div className="overview"><button className="next-card" onClick={()=>upcoming&&openEvent(upcoming)}><div className="soft-icon"><Clock size={21}/></div><div><span className="overline">БЛИЖАЙШЕЕ ЗАНЯТИЕ</span><b>{upcoming?.title||'Впереди свободное время'} <ArrowUpRight size={15}/></b><small>{upcoming?`${niceDate(upcoming.date,{day:'numeric',month:'short'})} · ${upcoming.time} · ${upcoming.location||SOURCES[upcoming.kind]}`:'Можно выдохнуть'}</small></div></button><div className="stat"><span>Уроки на неделе</span><b>{events.filter(e=>e.kind==='lesson').length}<small>занятий</small></b></div><div className="stat"><span>Время с учениками</span><b>{Math.round(events.filter(e=>e.kind==='lesson').reduce((n,e)=>n+e.duration,0)/60*10)/10}<small>часов</small></b></div><button className={'stat status-stat '+(clashIds.size?'has-conflict':'')} onClick={()=>setModal({type:'sources'})}><span>{clashIds.size?'Есть пересечения':'Проверка расписания'}</span><b>{clashIds.size?<><AlertCircle size={20}/>{clashIds.size}<small>занятий</small></>:<><CalendarCheck size={20}/><small>{unavailable.length?'Источники не подтверждены':'Неделя обновлена'}</small></>}</b></button></div>
 <div className="calendar-layout"><section className="calendar-panel"><div className="calendar-toolbar"><div className="date-nav"><Button className="icon-only" aria-label="Предыдущая неделя" onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft size={18}/></Button><Button className="icon-only" aria-label="Следующая неделя" onClick={()=>setWeek(addDays(week,7))}><ChevronRight size={18}/></Button><h2>{niceDate(week,{day:'numeric'})}–{niceDate(addDays(week,6),{day:'numeric',month:'long'})}<small>{tusurWeek?`${tusurWeek.number}-я учебная · ${tusurWeek.parity}`:niceDate(week,{year:'numeric'})}</small></h2><Button className="today-btn" onClick={()=>{setWeek(monday(today()));setSelected(today())}}>Сегодня</Button></div><div className="segmented"><button className={view==='week'?'selected':''} onClick={()=>setView('week')}>Неделя</button><button className={view==='agenda'?'selected':''} onClick={()=>setView('agenda')}>Список</button></div></div>
 <div className="legend-row"><div className="legend">{Object.entries(SOURCES).map(([key,label])=><button key={key} aria-pressed={filters.includes(key)} className={!filters.includes(key)?'muted':''} onClick={()=>setFilters(f=>f.includes(key)?f.filter(x=>x!==key):[...f,key])}><i className={'dot '+key}/>{key==='lesson'?'Ученики':key==='university'?'Пары':label}</button>)}</div><button className="text-button" onClick={()=>sync()} disabled={syncing}><RefreshCw size={13} className={syncing?'spin':''}/>{syncing?'Обновляем':'Обновить'}</button></div>
 {unavailable.length>0&&<button className="coverage-strip" onClick={()=>setModal({type:'sources'})}><AlertCircle size={13}/>{sources.some(x=>x.known)?'Часть источников требует обновления':'Пары и вождение ещё не подтверждены'}<ChevronRight size={13}/></button>}
 <div className={view==='agenda'?'agenda-view':'week-view'}><Calendar events={weekEvents} week={week} selected={selected} setSelected={setSelected} open={openEvent} add={newEvent} clashIds={clashIds} notes={data.notes}/></div>
 <div className={view==='agenda'?'agenda-list':'mobile-agenda'}>{Array.from({length:7},(_,i)=>addDays(week,i)).map(date=><section className="agenda-day" key={date}><h3>{niceDate(date,{weekday:'long',day:'numeric',month:'short'})}</h3>{weekEvents.filter(e=>e.date===date).length?weekEvents.filter(e=>e.date===date).map(e=><EventRow key={e.id} event={e} open={openEvent} conflict={clashIds.has(e.id)}/>):<button className="empty-day" onClick={()=>newEvent(date)}>Нет записей · Добавить</button>}</section>)}</div>
 <footer className="calendar-footer"><span>Время Томска · UTC+7</span><span>Нажми на пустой час, чтобы добавить занятие</span></footer></section>
 <aside className="day-panel"><div className="day-heading"><div className="eyebrow">ФОКУС НА ДЕНЬ</div><h2>{niceDate(selected,{day:'numeric',month:'long'})}</h2><small>{niceDate(selected,{weekday:'long'})}</small></div><div className="day-list">{dayEvents.length?dayEvents.map(e=><EventRow key={e.id} event={e} open={openEvent} conflict={clashIds.has(e.id)} compact/>):<div className="quiet-empty"><CalendarDays size={27}/><p>Пока нет записей</p></div>}</div><div className="window-card"><span className="overline"><Search size={14}/> ОКНО ДЛЯ УРОКА</span><h3>{slots.length?`${slots[0]}–${clock(minutes(slots[0])+60)}`:'Нет подходящих окон'}</h3><p>{coverage(cache,selected).every(x=>x.fresh)?'60 минут с учётом твоих перерывов.':'По сохранённым данным. Источники ещё нужно подтвердить.'}</p><button onClick={()=>setModal({type:'find'})}>Посмотреть варианты <ArrowRight size={15}/></button></div><div className="side-tip"><StickyNote size={16}/><p>После урока запиши пару строк. Перед следующим — просто открой карточку.</p></div></aside></div>
 {data.events.some(e=>e.provisional)&&<div className="footnote"><AlertCircle size={14}/> Уроки перенесены со скрина по 60 минут. Проверь длительность и дату начала в карточках.</div>}</>:page==='students'?<><div className="student-tools"><div className="search-input"><Search size={17}/><input placeholder="Найти ученика" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{data.students.length} учеников в твоём ритме</span></div><div className="student-table"><div className="student-table-head"><span>Ученик</span><span>На чём остановились</span><span>Следующий шаг</span><span>Ближайший урок</span></div>{data.students.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())).map((s,i)=>{const next=allSoon.find(e=>e.studentId===s.id&&instant(e.end)>Date.now());return <button className="student-row" key={s.id} onClick={()=>setModal({type:'student',student:s})}><span className="student-name"><span className={'avatar color'+i%4}>{s.name[0]}</span><b>{s.name}</b></span><span>{s.topic||'Добавь тему занятия'}</span><span>{s.next||'План пока не записан'}</span><span>{next?<>{niceDate(next.date,{day:'numeric',month:'short'})}<b>{next.time}</b></>:'Не назначен'}<ChevronRight size={15}/></span></button>})}</div></>:<SettingsPage data={data} save={save} saving={saving} connections={connections} cache={cache} openSources={()=>setModal({type:'sources'})}/>}
 </div></main>
 {message&&<div className="toast" role="status"><span>{message==='Сохранено'?<Check size={17}/>:<AlertCircle size={17}/>}</span>{message}<button aria-label="Скрыть сообщение" onClick={()=>setMessage('')}><X size={14}/></button></div>}
 {modal?.type==='event'&&<EventEditor data={data} cache={cache} initial={modal} saving={saving} save={save} sync={sync} onClose={()=>setModal(null)}/>}
 {modal?.type==='detail'&&<EventDetail event={modal.event} data={data} save={save} saving={saving} onClose={()=>setModal(null)} edit={()=>setModal({type:'event',event:modal.event,date:modal.event.date,time:modal.event.time})} student={id=>setModal({type:'student',student:data.students.find(s=>s.id===id)})}/>}
 {modal?.type==='student'&&<StudentEditor student={modal.student} data={data} save={save} saving={saving} onClose={()=>setModal(null)}/>}
 {modal?.type==='find'&&<FindTime data={data} cache={cache} initialWeek={week} onClose={()=>setModal(null)} choose={(date,time,duration)=>setModal({type:'event',date,time,duration})} sync={sync}/>}
 {modal?.type==='sources'&&<Modal title="Источники расписания" subtitle={`${niceDate(week)} — ${niceDate(addDays(week,6))}`} onClose={()=>setModal(null)}><div className="modal-body">{sources.map(({source,record,fresh})=><div className="source-card" key={source}><h3>{source==='university'?<GraduationCap size={20}/>:<Car size={20}/>} {source==='university'?'ТУСУР · 435-2':'Автошкола'}</h3><span className={'badge '+(fresh?'success':'warning')}>{fresh?'Неделя загружена':record?.lastSuccess?'Сохранённая версия':'Нет подтверждённых данных'}</span><p>{record?.error||'Обновляется при входе, смене недели и каждые 15 минут.'}</p><small>{record?.lastSuccess?'Последний успех: '+new Date(record.lastSuccess).toLocaleString('ru-RU',{timeZone:'Asia/Tomsk'}):'Успешных обновлений ещё не было'}</small>{record?.week&&<p>Учебная неделя {record.week.number} · {record.week.parity}</p>}</div>)}<p className="helper">Сбой источника не удаляет сохранённые занятия. Отсутствие данных не означает, что время свободно.</p></div><div className="modal-actions"><Button icon={RefreshCw} disabled={syncing} onClick={()=>sync()}>{syncing?'Обновляем…':'Обновить эту неделю'}</Button></div></Modal>}
 </div>;
}
function Login({onLogin}){const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login-page"><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('login','POST',{password});onLogin();}catch(e){setError(e.message)}finally{setBusy(false)}}}><span className="brand-icon"><Activity size={30}/></span><h1>Вернись в свой ритм.</h1><p>Твоё время. Твои ученики. Всё на месте.</p><Field label="Пароль"><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></Field>{error&&<p className="error">{error}</p>}<Button className="primary" disabled={busy}>Войти <ArrowRight size={17}/></Button></form></div>}
function EventRow({event:e,open,conflict,compact=false}){const Icon=icons[e.kind];return <button className={'event-row '+(compact?'compact ':'')+e.kind} onClick={()=>open(e)}><span className="row-time">{e.time}</span><span className="event-row-line"/><div><b>{e.title}</b><small>{e.location||SOURCES[e.kind]}{conflict?' · Пересечение':''}</small></div>{!compact&&<Icon size={17}/>}</button>}
function Calendar({events,week,selected,setSelected,open,add,clashIds,notes}){
 const days=Array.from({length:7},(_,i)=>addDays(week,i));
 const minHour=Math.min(8,...events.map(e=>Math.floor(minutes(e.time)/60))),hours=24-minHour,scale=52;
 const nowTime=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tomsk',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
 return <div className="calendar-scroll"><div className="calendar-grid"><div className="grid-head"><div className="timezone">GMT+7</div>{days.map((d,i)=><button key={d} className={(d===today()?'is-today ':'')+(d===selected?'day-selected':'')} onClick={()=>setSelected(d)}><span>{DAYS[i]}</span><b>{Number(d.slice(8))}</b></button>)}</div><div className="grid-body" style={{height:hours*scale}}><div className="time-gutter">{Array.from({length:hours},(_,i)=><span key={i} style={{top:i*scale}}>{clock((minHour+i)*60)}</span>)}</div>{days.map(d=>{const list=events.filter(e=>e.date===d),lanes=eventLanes(list);return <div className={'day-column '+(d===selected?'day-selected':'')} key={d}>{Array.from({length:hours},(_,h)=><button key={h} className="hour-cell" style={{height:scale}} aria-label={`Добавить ${d} ${clock((h+minHour)*60)}`} onClick={()=>add(d,clock((h+minHour)*60))}/>)}{list.map(e=>{const {lane:idx,count}=lanes.get(e.id);return <button key={e.id} className={'calendar-event '+e.kind+(clashIds.has(e.id)?' conflict':'')} style={{top:(minutes(e.time)-minHour*60)*scale/60+2,height:Math.max(25,Math.min(e.duration,1440-minutes(e.time))*scale/60-4),left:`calc(${idx*100/count}% + 4px)`,width:`calc(${100/count}% - 8px)`}} onClick={()=>open(e)} title={`${e.title} · ${e.time}–${e.end.slice(11)}${e.location?' · '+e.location:''}`}><span>{e.time}–{e.end.slice(11)}{notes[e.id]?.prepared&&<Check size={11}/>}</span><b>{e.title}</b><small>{e.location||SOURCES[e.kind]}</small>{(notes[e.id]?.text||e.note)&&<StickyNote className="note-dot" size={11}/>}</button>})}{d===today()&&minutes(nowTime)>=minHour*60&&<div className="now-line" style={{top:(minutes(nowTime)-minHour*60)*scale/60}}/>}</div>})}</div></div></div>
}
function EventEditor({data,cache,initial,onClose,save,saving,sync}){
 const existing=initial.event,rule=existing&&data.events.find(e=>e.id===existing.ruleId);
 const [form,setForm]=useState(rule?{...rule,date:existing.date}:{id:uid(),title:'',studentId:'',kind:'lesson',date:initial.date,time:initial.time,duration:initial.duration||60,repeat:'none',until:'',exceptions:[],location:'Онлайн',note:''});
 const [scope,setScope]=useState('one'),[ack,setAck]=useState(false),[checking,setChecking]=useState(false),[error,setError]=useState('');
 const update=(key,value)=>{setForm(f=>({...f,[key]:value}));setAck(false)};
 const from=monday(form.date||today()),to=addDays(from,56),checkEvents=occurrences(data,addDays(from,-1),addDays(to,1),cache);
 const dates=form.date?Array.from({length:form.repeat==='weekly'&&(!rule||scope==='future')?8:1},(_,i)=>addDays(form.date,i*7)).filter(d=>!form.until||d<=form.until):[];
 const issues=dates.flatMap(date=>{const endMinutes=minutes(form.time)+Number(form.duration),candidate={...form,start:stamp(date,form.time),end:stamp(addDays(date,Math.floor(endMinutes/1440)),clock(endMinutes%1440))};return conflicts(candidate,checkEvents.filter(e=>!rule||!(e.ruleId===rule.id&&(scope==='future'?e.date>=existing.date:e.date===existing.date))),data.settings).map(c=>({...c,date}));});
 const uncertain=dates.filter(d=>coverage(cache,d).some(x=>!x.fresh));
 const outside=minutes(form.time)<minutes(data.settings.workStart)||minutes(form.time)+Number(form.duration)>minutes(data.settings.workEnd);
 async function submit(e){e.preventDefault();setError('');if(issues.length)return;const student=data.students.find(s=>s.id===form.studentId),item={...form,title:student?.name||form.title.trim(),duration:Number(form.duration),provisional:false};if(!item.title){setError('Укажи название или выбери ученика');return;}if(form.until&&form.until<form.date){setError('Конец повторения раньше начала');return;}let events=[...data.events];if(rule){events=events.map(r=>r.id===rule.id?(scope==='one'?{...r,exceptions:[...new Set([...r.exceptions,existing.date])]}:{...r,until:addDays(existing.date,-1)}):r);if(scope==='future'&&existing.date===rule.date)events=events.filter(r=>r.id!==rule.id);item.id=uid();item.repeat=scope==='one'?'none':form.repeat;item.exceptions=[];}const next={...data,events:[...events,item]};if(rule&&data.notes[existing.id])next.notes={...data.notes,[item.id+'@'+item.date]:data.notes[existing.id]};if(await save(next))onClose();}
 return <Modal title={rule?'Перенести или изменить':'Новое занятие'} subtitle="Сначала проверим время — потом сохраним." onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="kind-picker">{Object.entries(SOURCES).map(([k,label])=><button type="button" className={form.kind===k?'selected '+k:''} key={k} onClick={()=>{setForm(f=>({...f,kind:k,studentId:k==='lesson'?f.studentId:''}));setAck(false)}}>{label}</button>)}</div>{rule?.repeat==='weekly'&&<Field label="Что изменить"><select value={scope} onChange={e=>setScope(e.target.value)}><option value="one">Только это занятие</option><option value="future">Это и последующие</option></select></Field>}
 {form.kind==='lesson'&&<Field label="Ученик"><select value={form.studentId} onChange={e=>update('studentId',e.target.value)}><option value="">Без привязки к ученику</option>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>}{!form.studentId&&<Field label="Название"><input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Например, очное занятие" required maxLength={200}/></Field>}
 <div className="form-grid"><Field label="Дата"><input type="date" value={form.date} required onChange={e=>update('date',e.target.value)}/></Field><Field label="Начало · Томск"><input type="time" value={form.time} required onChange={e=>update('time',e.target.value)}/></Field><Field label="Длительность, минут"><input type="number" min="5" max="720" value={form.duration} required onChange={e=>update('duration',Number(e.target.value))}/></Field><Field label="Повторять"><select disabled={rule&&scope==='one'} value={rule&&scope==='one'?'none':form.repeat} onChange={e=>update('repeat',e.target.value)}><option value="none">Один раз</option><option value="weekly">Каждую неделю</option></select></Field></div>{form.repeat==='weekly'&&(!rule||scope==='future')&&<Field label="До даты (необязательно)"><input type="date" min={form.date} value={form.until} onChange={e=>update('until',e.target.value)}/></Field>}
 <Field label="Место или ссылка"><input value={form.location} onChange={e=>update('location',e.target.value)}/></Field><Field label="Заметка к занятию"><textarea rows="2" value={form.note} onChange={e=>update('note',e.target.value)} placeholder="Что подготовить, что не забыть…"/></Field>
 <div className={'check-result '+(issues.length?'bad':uncertain.length||outside?'caution':'good')}><b>{issues.length?<><AlertCircle size={17}/> Это время занято</>:<><CalendarCheck size={17}/>{uncertain.length?'По записям пересечений нет':'Время подходит'}</>}</b>{issues.slice(0,4).map((x,i)=><p key={i}>{niceDate(x.date,{day:'numeric',month:'short'})} · {x.event.time} {x.event.title}{x.type==='buffer'?' — нужен перерыв или дорога':''}</p>)}{!issues.length&&<p>{dates.length>1?`Проверено ${dates.length} ближайших повторений. `:''}{uncertain.length?`На ${uncertain.length} датах источники не подтверждены.`:'С учётом перерывов и дороги.'}</p>}{outside&&<p>Занятие выходит за твои рабочие часы.</p>}</div>
 {dates.length>1&&<><button className="text-button" type="button" disabled={checking} onClick={async()=>{setChecking(true);try{for(const d of dates)await sync(monday(d));}finally{setChecking(false)}}}><RefreshCw size={14} className={checking?'spin':''}/>{checking?'Загружаем недели…':'Обновить все проверяемые недели'}</button><p className="helper">Проверка ограничена 8 ближайшими неделями. Более поздние изменения отслеживаются при синхронизации.</p></>}
 {!!(uncertain.length||outside)&&!issues.length&&<label className="checkbox"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Сохранить с учётом предупреждений</label>}{error&&<p className="error">{error}</p>}</div><div className="modal-actions"><Button type="button" onClick={onClose}>Отмена</Button><Button className="primary" disabled={saving||checking||!!issues.length||((!!uncertain.length||outside)&&!ack)}>{saving?'Сохраняем…':rule?'Сохранить изменения':'Добавить занятие'}</Button></div></form></Modal>
}
function EventDetail({event:e,data,save,saving,onClose,edit,student}){
 const old=data.notes[e.id]||{text:e.note||'',prepared:false},[text,setText]=useState(old.text),[prepared,setPrepared]=useState(old.prepared),[cancel,setCancel]=useState(false);
 const s=data.students.find(s=>s.id===e.studentId),Icon=icons[e.kind];
 async function persist(){if(await save({...data,notes:{...data.notes,[e.id]:{text,prepared}}}))onClose();}
 async function remove(scope){const events=data.events.flatMap(r=>r.id!==e.ruleId?[r]:scope==='one'?[{...r,exceptions:[...new Set([...r.exceptions,e.date])]}]:e.date===r.date?[]:[{...r,until:addDays(e.date,-1)}]);if(await save({...data,events}))onClose();}
 return <Modal title={e.title} subtitle={`${niceDate(e.date,{weekday:'long',day:'numeric',month:'long'})} · ${e.time}–${e.end.slice(11)}`} onClose={onClose}><div className="modal-body"><div className={'detail-kind '+e.kind}><Icon size={18}/>{SOURCES[e.kind]} {e.external&&<span>из расписания</span>}</div>{e.location&&<p className="location"><MapPin size={16}/>{e.location}</p>}{e.provisional&&<p className="helper">Длительность 60 минут взята как предположение. Нажми «Изменить», чтобы уточнить.</p>}{s&&<div className="lesson-brief"><div><span>ОСТАНОВИЛИСЬ НА</span><p>{s.topic||'Пока нет записей'}</p></div><div><span>ДОМАШНЕЕ ЗАДАНИЕ</span><p>{s.homework||'Не записано'}</p></div><div><span>ПЛАН НА УРОК</span><p>{s.next||'Добавь план в карточке ученика'}</p></div><button className="text-button" onClick={()=>student(s.id)}>Карточка ученика и итоги <ArrowUpRight size={15}/></button></div>}{e.sourceNote&&<details className="source-details" open><summary>Из источника · аудитория и комментарии</summary><p>{e.sourceNote}</p></details>}<Field label="Моя заметка"><textarea rows="5" value={text} onChange={ev=>setText(ev.target.value)} placeholder="Любые детали к этому занятию…"/></Field><label className="checkbox"><input type="checkbox" checked={prepared} onChange={ev=>setPrepared(ev.target.checked)}/>Материалы подготовлены</label>{e.external&&<p className="helper">Эта заметка сохранится при обновлении расписания.</p>}{cancel&&<div className="cancel-options"><p>Отменить занятие?</p><Button onClick={()=>remove('one')} disabled={saving}>Только это</Button><Button onClick={()=>remove('future')} disabled={saving}>Это и последующие</Button></div>}</div><div className="modal-actions spread"><div>{!e.external&&<><Button onClick={edit}>Изменить</Button><button className="text-button danger" onClick={()=>setCancel(!cancel)}>Отменить</button></>}</div><Button className="primary" icon={Check} onClick={persist} disabled={saving}>{saving?'Сохраняем…':'Сохранить заметку'}</Button></div></Modal>
}
function StudentEditor({student,data,save,saving,onClose}){
 const [form,setForm]=useState(student?{...student}:{id:uid(),name:'',topic:'',homework:'',next:'',materials:'',notes:'',history:[]}),[tab,setTab]=useState('context'),[log,setLog]=useState({date:today(),done:'',homework:'',next:''});
 const update=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function submit(e){e.preventDefault();let item={...form};if(tab==='log'&&(log.done||log.homework||log.next)){item={...item,topic:log.done||item.topic,homework:log.homework,next:log.next,history:[{...log,id:uid()},...item.history]};}if(await save({...data,students:student?data.students.map(s=>s.id===item.id?item:s):[...data.students,item]}))onClose();}
 return <Modal title={student?student.name:'Новый ученик'} subtitle="Контекст, который не нужно держать в голове." onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="tabs"><button type="button" className={tab==='context'?'selected':''} onClick={()=>setTab('context')}>Карточка</button><button type="button" className={tab==='log'?'selected':''} onClick={()=>setTab('log')}>Итоги урока</button><button type="button" className={tab==='history'?'selected':''} onClick={()=>setTab('history')}>История <span>{form.history.length}</span></button></div>
 {tab==='context'?<><Field label="Имя"><input value={form.name} required maxLength={120} onChange={e=>update('name',e.target.value)}/></Field>{[['topic','На чём остановились','Что уже получается, где возникают ошибки'],['homework','Домашнее задание','Что проверить на следующем уроке'],['next','Следующий урок','План, задачи и материалы'],['materials','Ссылки на материалы','Ссылки или названия файлов'],['notes','Общие заметки','Цель подготовки, особенности ученика']].map(([key,label,placeholder])=><Field label={label} key={key}><textarea rows="2" value={form[key]} placeholder={placeholder} onChange={e=>update(key,e.target.value)}/></Field>)}</>:tab==='log'?<><p className="helper">Три короткие записи обновят карточку и останутся в истории.</p>{!form.name&&<Field label="Имя"><input required value={form.name} onChange={e=>update('name',e.target.value)}/></Field>}<Field label="Дата урока"><input type="date" required value={log.date} onChange={e=>setLog({...log,date:e.target.value})}/></Field>{[['done','Что прошли'],['homework','Что задали'],['next','Что дальше']].map(([k,label])=><Field key={k} label={label}><textarea rows="3" value={log[k]} onChange={e=>setLog({...log,[k]:e.target.value})}/></Field>)}</>:form.history.length?form.history.map(h=><article className="history-item" key={h.id}><b>{niceDate(h.date)}</b><p>{h.done}</p>{h.homework&&<p><small>ДОМАШКА</small>{h.homework}</p>}{h.next&&<p><small>ДАЛЬШЕ</small>{h.next}</p>}</article>):<div className="quiet-empty"><BookOpen size={30}/><h3>История начинается с урока</h3><p>Добавь первую запись во вкладке «Итоги урока».</p></div>}</div><div className="modal-actions"><Button type="button" onClick={onClose}>Закрыть</Button><Button className="primary" disabled={saving||!form.name.trim()}>{saving?'Сохраняем…':tab==='log'?'Сохранить итоги':'Сохранить карточку'}</Button></div></form></Modal>
}
function FindTime({data,cache,initialWeek,onClose,choose,sync}){
 const [week,setWeek]=useState(initialWeek),[duration,setDuration]=useState(60),[after,setAfter]=useState('16:00'),[checking,setChecking]=useState(false);
 const events=occurrences(data,addDays(week,-1),addDays(week,8),cache);
 return <Modal title="Найдём время для урока" subtitle="Все занятия, перерывы и дорога уже учтены." onClose={onClose} wide><div className="modal-body"><div className="find-controls"><Button aria-label="Раньше" onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft size={16}/></Button><b>{niceDate(week,{day:'numeric',month:'short'})} — {niceDate(addDays(week,6),{day:'numeric',month:'short'})}</b><Button aria-label="Позже" onClick={()=>setWeek(addDays(week,7))}><ChevronRight size={16}/></Button></div><div className="form-grid"><Field label="Длительность"><select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[30,45,60,90,120].map(n=><option key={n} value={n}>{n} минут</option>)}</select></Field><Field label="Не раньше"><input type="time" value={after} onChange={e=>setAfter(e.target.value)}/></Field></div>{coverage(cache,week).some(x=>!x.fresh)&&<div className="check-result caution"><b><AlertCircle size={16}/> Окна предварительные</b><p>Есть неподтверждённые источники на этой неделе.</p><button className="text-button" disabled={checking} onClick={async()=>{setChecking(true);await sync(week);setChecking(false)}}>{checking?'Обновляем…':'Обновить выбранную неделю'}</button></div>}
 <div className="slot-list">{Array.from({length:7},(_,i)=>addDays(week,i)).map(date=>{const slots=freeSlots(data,events,date,duration).filter(t=>t>=after&&instant(stamp(date,t))>Date.now());return <div key={date}><b>{DAYS[weekday(date)]}<small>{niceDate(date,{day:'numeric',month:'short'})}</small></b><div>{slots.length?slots.map(t=><button key={t} onClick={()=>choose(date,t,duration)}>{t}</button>):<span className="helper">Нет подходящих окон</span>}</div></div>})}</div></div></Modal>
}
function SettingsPage({data,save,saving,connections,cache,openSources}){
 const [form,setForm]=useState({...data.settings}),[error,setError]=useState('');const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <div className="settings-grid"><form className="settings-card" onSubmit={e=>{e.preventDefault();if(form.workEnd<=form.workStart){setError('Окончание должно быть позже начала');return;}setError('');save({...data,settings:form});}}><h2><SlidersHorizontal size={19}/> Границы твоего дня</h2><p>По этим правилам мы ищем окна и проверяем занятия.</p><div className="form-grid"><Field label="Можно начинать с"><input type="time" required value={form.workStart} onChange={e=>update('workStart',e.target.value)}/></Field><Field label="Заканчивать до"><input type="time" required value={form.workEnd} onChange={e=>update('workEnd',e.target.value)}/></Field><Field label="Перерыв между уроками, мин"><input type="number" min="0" max="120" value={form.breakMinutes} onChange={e=>update('breakMinutes',Number(e.target.value))}/></Field><Field label="Дорога до / после пар и вождения, мин"><input type="number" min="0" max="180" value={form.travelMinutes} onChange={e=>update('travelMinutes',Number(e.target.value))}/></Field></div><Field label="Подгруппа ТУСУР"><select value={form.subgroup} onChange={e=>update('subgroup',e.target.value)}><option value="all">Все — пока не выбрана</option><option value="а">Подгруппа А</option><option value="б">Подгруппа Б</option></select></Field><p className="helper">Занятия без указания подгруппы остаются видны всегда.</p><Field label="Напоминать за, минут (0 — выключить)"><input type="number" min="0" max="120" value={form.reminderMinutes} onChange={e=>update('reminderMinutes',Number(e.target.value))}/></Field>{error&&<p className="error">{error}</p>}<Button className="primary" disabled={saving}>Сохранить настройки</Button></form><div><section className="settings-card"><h2><RefreshCw size={19}/> Подключения</h2><div className="connection"><span><GraduationCap size={20}/><b>ТУСУР<small>Группа 435-2 · конкретные недели</small></b></span><span className="badge neutral">Подключён</span></div><div className="connection"><span><Car size={20}/><b>Автошкола<small>Только мои занятия</small></b></span><span className={'badge '+(connections.driving?'success':'warning')}>{connections.driving?'Настроено':'Нужен Cookie'}</span></div><div className="connection"><span><Clock size={20}/><b>Напоминания<small>Telegram · при закрытом сайте</small></b></span><span className={'badge '+(connections.telegram?'success':'neutral')}>{connections.telegram?'Настроено':'Не подключены'}</span></div><p className="helper">Автошкола и Telegram подключаются в .env сервера. Секреты не хранятся в браузере.</p><Button onClick={openSources}>Состояние текущей недели</Button></section><section className="settings-card"><h2><Download size={19}/> Твои данные</h2><p>Резервная копия учеников, уроков, заметок и сохранённых расписаний.</p><a className="btn" href="/api/export" download><Download size={16}/> Скачать JSON</a><p className="helper">Основная база — на сервере. В браузере хранится последняя копия для просмотра без связи.</p></section></div></div>
}
if(document.getElementById('root'))createRoot(document.getElementById('root')).render(<App/>);

export {App,Calendar,EventEditor,EventDetail,StudentEditor,FindTime};
